name: Run Tests
on: [push, pull_request]
jobs:
  build:
    name: hello welcome
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g vsce
          npm install

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test

      - name: package artifact
        run: |
          CURRENT_VERSION=$(cat package.json | jq .version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          GIT_COMMIT=$(git rev-parse --short HEAD)
          vsce package -o hello_welcome-$CURRENT_VERSION.vsix
          ls -l 

      - name: Upload vsix artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello_welcome
          path: ${{ github.workspace }}/*.vsix

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          # GHR_COMPRESS: zip
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           